[pytest]
DJANGO_SETTINGS_MODULE = bloggin_system.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    --cov=bloggin_system/service
    --reuse-db
    --disable-warnings
    -ra
    --tb=short
    --maxfail=5
    --durations=10
testpaths = bloggin_system/service/tests
